const REQUESTED = 'REQUESTED';
const APPROVED = 'APPROVED';
const REJECTED = 'REJECTED';
const COMPLETED = 'COMPLETED';
const CANCELED = 'CANCELED';

module.exports = {
  REQUESTED,
  APPROVED,
  REJECTED,
  COMPLETED,
  CANCELED,
}